services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y portaudio19-dev
      poetry install
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    pythonVersion: 3.10
